/******************************************************************************
 * This file was generated by langium-cli 4.2.0.
 * DO NOT EDIT MANUALLY!
 ******************************************************************************/

/* eslint-disable */
import * as langium from 'langium';

export const AtlasTerminals = {
    FLOAT: /[0-9]+\.[0-9]+/,
    WS: /\s+/,
    PACK_ID: /[a-zA-Z][a-zA-Z0-9]*(-[a-zA-Z0-9]+)*/,
    INT: /[0-9]+/,
    STRING: /"(\\.|[^"\\])*"|'(\\.|[^'\\])*'/,
    ML_COMMENT: /\/\*[\s\S]*?\*\//,
    SL_COMMENT: /\/\/[^\n\r]*/,
};

export type AtlasTerminalNames = keyof typeof AtlasTerminals;

export type AtlasKeywordNames =
    | ","
    | "["
    | "]"
    | "author"
    | "category"
    | "color"
    | "description"
    | "duration"
    | "energy"
    | "fluid"
    | "form"
    | "game"
    | "gameVersion"
    | "gamepack"
    | "gas"
    | "hr"
    | "icon"
    | "in"
    | "input"
    | "item"
    | "label"
    | "min"
    | "moduleSlots"
    | "name"
    | "node"
    | "nodes"
    | "out"
    | "output"
    | "parent"
    | "port"
    | "power"
    | "recipe"
    | "sec"
    | "solid"
    | "sortOrder"
    | "speed"
    | "tags"
    | "url"
    | "version"
    | "{"
    | "}";

export type AtlasTokenNames = AtlasTerminalNames | AtlasKeywordNames;

export interface Category extends langium.AstNode {
    readonly $container: Gamepack;
    readonly $type: 'Category';
    color: Array<string>;
    description: Array<string>;
    icon: Array<string>;
    id: string;
    name: Array<string>;
    parent: Array<langium.Reference<Category>>;
    sortOrder: Array<number>;
}

export const Category = {
    $type: 'Category',
    color: 'color',
    description: 'description',
    icon: 'icon',
    id: 'id',
    name: 'name',
    parent: 'parent',
    sortOrder: 'sortOrder'
} as const;

export function isCategory(item: unknown): item is Category {
    return reflection.isInstance(item, Category.$type);
}

export type DurationUnit = 'hr' | 'min' | 'sec';

export function isDurationUnit(item: unknown): item is DurationUnit {
    return item === 'sec' || item === 'min' || item === 'hr';
}

export interface Gamepack extends langium.AstNode {
    readonly $type: 'Gamepack';
    author: Array<string>;
    categories: Array<Category>;
    description: Array<string>;
    gameName: Array<string>;
    gameVersion: Array<string>;
    id: string;
    items: Array<Item>;
    name: Array<string>;
    nodeTemplates: Array<NodeTemplate>;
    recipes: Array<Recipe>;
    url: Array<string>;
    version: Array<string>;
}

export const Gamepack = {
    $type: 'Gamepack',
    author: 'author',
    categories: 'categories',
    description: 'description',
    gameName: 'gameName',
    gameVersion: 'gameVersion',
    id: 'id',
    items: 'items',
    name: 'name',
    nodeTemplates: 'nodeTemplates',
    recipes: 'recipes',
    url: 'url',
    version: 'version'
} as const;

export function isGamepack(item: unknown): item is Gamepack {
    return reflection.isInstance(item, Gamepack.$type);
}

export interface IngredientSpec extends langium.AstNode {
    readonly $container: Recipe;
    readonly $type: 'IngredientSpec';
    amount: Num;
    item: langium.Reference<Item>;
}

export const IngredientSpec = {
    $type: 'IngredientSpec',
    amount: 'amount',
    item: 'item'
} as const;

export function isIngredientSpec(item: unknown): item is IngredientSpec {
    return reflection.isInstance(item, IngredientSpec.$type);
}

export interface Item extends langium.AstNode {
    readonly $container: Gamepack;
    readonly $type: 'Item';
    category: Array<langium.Reference<Category>>;
    color: Array<string>;
    description: Array<string>;
    form: Array<ItemForm>;
    icon: Array<string>;
    id: string;
    name: Array<string>;
}

export const Item = {
    $type: 'Item',
    category: 'category',
    color: 'color',
    description: 'description',
    form: 'form',
    icon: 'icon',
    id: 'id',
    name: 'name'
} as const;

export function isItem(item: unknown): item is Item {
    return reflection.isInstance(item, Item.$type);
}

export type ItemForm = 'energy' | 'fluid' | 'gas' | 'solid';

export function isItemForm(item: unknown): item is ItemForm {
    return item === 'solid' || item === 'fluid' || item === 'gas' || item === 'energy';
}

export interface NodeTemplate extends langium.AstNode {
    readonly $container: Gamepack;
    readonly $type: 'NodeTemplate';
    category: Array<langium.Reference<Category>>;
    color: Array<string>;
    description: Array<string>;
    icon: Array<string>;
    id: string;
    moduleSlots: Array<number>;
    name: Array<string>;
    ports: Array<PortDef>;
    power: Array<Num>;
    speed: Array<Num>;
    tags: Array<string>;
}

export const NodeTemplate = {
    $type: 'NodeTemplate',
    category: 'category',
    color: 'color',
    description: 'description',
    icon: 'icon',
    id: 'id',
    moduleSlots: 'moduleSlots',
    name: 'name',
    ports: 'ports',
    power: 'power',
    speed: 'speed',
    tags: 'tags'
} as const;

export function isNodeTemplate(item: unknown): item is NodeTemplate {
    return reflection.isInstance(item, NodeTemplate.$type);
}

export type Num = number;

export function isNum(item: unknown): item is Num {
    return typeof item === 'number';
}

export interface PortDef extends langium.AstNode {
    readonly $container: NodeTemplate;
    readonly $type: 'PortDef';
    direction: PortDirection;
    id: string;
    label?: string;
}

export const PortDef = {
    $type: 'PortDef',
    direction: 'direction',
    id: 'id',
    label: 'label'
} as const;

export function isPortDef(item: unknown): item is PortDef {
    return reflection.isInstance(item, PortDef.$type);
}

export type PortDirection = 'input' | 'output';

export function isPortDirection(item: unknown): item is PortDirection {
    return item === 'input' || item === 'output';
}

export interface ProductSpec extends langium.AstNode {
    readonly $container: Recipe;
    readonly $type: 'ProductSpec';
    amount: Num;
    item: langium.Reference<Item>;
}

export const ProductSpec = {
    $type: 'ProductSpec',
    amount: 'amount',
    item: 'item'
} as const;

export function isProductSpec(item: unknown): item is ProductSpec {
    return reflection.isInstance(item, ProductSpec.$type);
}

export interface Recipe extends langium.AstNode {
    readonly $container: Gamepack;
    readonly $type: 'Recipe';
    category: Array<langium.Reference<Category>>;
    color: Array<string>;
    compatibleNodes: Array<langium.Reference<NodeTemplate>>;
    compatibleTags: Array<string>;
    description: Array<string>;
    duration: Array<Num>;
    icon: Array<string>;
    id: string;
    inputs: Array<IngredientSpec>;
    name: Array<string>;
    outputs: Array<ProductSpec>;
    unit: Array<DurationUnit>;
}

export const Recipe = {
    $type: 'Recipe',
    category: 'category',
    color: 'color',
    compatibleNodes: 'compatibleNodes',
    compatibleTags: 'compatibleTags',
    description: 'description',
    duration: 'duration',
    icon: 'icon',
    id: 'id',
    inputs: 'inputs',
    name: 'name',
    outputs: 'outputs',
    unit: 'unit'
} as const;

export function isRecipe(item: unknown): item is Recipe {
    return reflection.isInstance(item, Recipe.$type);
}

export type AtlasAstType = {
    Category: Category
    Gamepack: Gamepack
    IngredientSpec: IngredientSpec
    Item: Item
    NodeTemplate: NodeTemplate
    PortDef: PortDef
    ProductSpec: ProductSpec
    Recipe: Recipe
}

export class AtlasAstReflection extends langium.AbstractAstReflection {
    override readonly types = {
        Category: {
            name: Category.$type,
            properties: {
                color: {
                    name: Category.color,
                    defaultValue: []
                },
                description: {
                    name: Category.description,
                    defaultValue: []
                },
                icon: {
                    name: Category.icon,
                    defaultValue: []
                },
                id: {
                    name: Category.id
                },
                name: {
                    name: Category.name,
                    defaultValue: []
                },
                parent: {
                    name: Category.parent,
                    defaultValue: [],
                    referenceType: Category.$type
                },
                sortOrder: {
                    name: Category.sortOrder,
                    defaultValue: []
                }
            },
            superTypes: []
        },
        Gamepack: {
            name: Gamepack.$type,
            properties: {
                author: {
                    name: Gamepack.author,
                    defaultValue: []
                },
                categories: {
                    name: Gamepack.categories,
                    defaultValue: []
                },
                description: {
                    name: Gamepack.description,
                    defaultValue: []
                },
                gameName: {
                    name: Gamepack.gameName,
                    defaultValue: []
                },
                gameVersion: {
                    name: Gamepack.gameVersion,
                    defaultValue: []
                },
                id: {
                    name: Gamepack.id
                },
                items: {
                    name: Gamepack.items,
                    defaultValue: []
                },
                name: {
                    name: Gamepack.name,
                    defaultValue: []
                },
                nodeTemplates: {
                    name: Gamepack.nodeTemplates,
                    defaultValue: []
                },
                recipes: {
                    name: Gamepack.recipes,
                    defaultValue: []
                },
                url: {
                    name: Gamepack.url,
                    defaultValue: []
                },
                version: {
                    name: Gamepack.version,
                    defaultValue: []
                }
            },
            superTypes: []
        },
        IngredientSpec: {
            name: IngredientSpec.$type,
            properties: {
                amount: {
                    name: IngredientSpec.amount
                },
                item: {
                    name: IngredientSpec.item,
                    referenceType: Item.$type
                }
            },
            superTypes: []
        },
        Item: {
            name: Item.$type,
            properties: {
                category: {
                    name: Item.category,
                    defaultValue: [],
                    referenceType: Category.$type
                },
                color: {
                    name: Item.color,
                    defaultValue: []
                },
                description: {
                    name: Item.description,
                    defaultValue: []
                },
                form: {
                    name: Item.form,
                    defaultValue: []
                },
                icon: {
                    name: Item.icon,
                    defaultValue: []
                },
                id: {
                    name: Item.id
                },
                name: {
                    name: Item.name,
                    defaultValue: []
                }
            },
            superTypes: []
        },
        NodeTemplate: {
            name: NodeTemplate.$type,
            properties: {
                category: {
                    name: NodeTemplate.category,
                    defaultValue: [],
                    referenceType: Category.$type
                },
                color: {
                    name: NodeTemplate.color,
                    defaultValue: []
                },
                description: {
                    name: NodeTemplate.description,
                    defaultValue: []
                },
                icon: {
                    name: NodeTemplate.icon,
                    defaultValue: []
                },
                id: {
                    name: NodeTemplate.id
                },
                moduleSlots: {
                    name: NodeTemplate.moduleSlots,
                    defaultValue: []
                },
                name: {
                    name: NodeTemplate.name,
                    defaultValue: []
                },
                ports: {
                    name: NodeTemplate.ports,
                    defaultValue: []
                },
                power: {
                    name: NodeTemplate.power,
                    defaultValue: []
                },
                speed: {
                    name: NodeTemplate.speed,
                    defaultValue: []
                },
                tags: {
                    name: NodeTemplate.tags,
                    defaultValue: []
                }
            },
            superTypes: []
        },
        PortDef: {
            name: PortDef.$type,
            properties: {
                direction: {
                    name: PortDef.direction
                },
                id: {
                    name: PortDef.id
                },
                label: {
                    name: PortDef.label
                }
            },
            superTypes: []
        },
        ProductSpec: {
            name: ProductSpec.$type,
            properties: {
                amount: {
                    name: ProductSpec.amount
                },
                item: {
                    name: ProductSpec.item,
                    referenceType: Item.$type
                }
            },
            superTypes: []
        },
        Recipe: {
            name: Recipe.$type,
            properties: {
                category: {
                    name: Recipe.category,
                    defaultValue: [],
                    referenceType: Category.$type
                },
                color: {
                    name: Recipe.color,
                    defaultValue: []
                },
                compatibleNodes: {
                    name: Recipe.compatibleNodes,
                    defaultValue: [],
                    referenceType: NodeTemplate.$type
                },
                compatibleTags: {
                    name: Recipe.compatibleTags,
                    defaultValue: []
                },
                description: {
                    name: Recipe.description,
                    defaultValue: []
                },
                duration: {
                    name: Recipe.duration,
                    defaultValue: []
                },
                icon: {
                    name: Recipe.icon,
                    defaultValue: []
                },
                id: {
                    name: Recipe.id
                },
                inputs: {
                    name: Recipe.inputs,
                    defaultValue: []
                },
                name: {
                    name: Recipe.name,
                    defaultValue: []
                },
                outputs: {
                    name: Recipe.outputs,
                    defaultValue: []
                },
                unit: {
                    name: Recipe.unit,
                    defaultValue: []
                }
            },
            superTypes: []
        }
    } as const satisfies langium.AstMetaData
}

export const reflection = new AtlasAstReflection();
