import { type Module, inject, type AstNode, DefaultNameProvider } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { AtlasGeneratedModule, AtlasGeneratedSharedModule } from './module.js';
import { AtlasValidator, registerValidationChecks } from './atlas-validator.js';
import { isCategory, isItem, isNodeTemplate, isRecipe } from './ast.js';

/**
 * All named nodes in Atlas use 'id' as the cross-reference key rather than 'name'.
 */
class AtlasNameProvider extends DefaultNameProvider {
    override getName(node: AstNode): string | undefined {
        if (isCategory(node))     return node.id;
        if (isItem(node))         return node.id;
        if (isNodeTemplate(node)) return node.id;
        if (isRecipe(node))       return node.id;
        return super.getName(node);
    }
}

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AtlasAddedServices = {
    validation: {
        AtlasValidator: AtlasValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AtlasServices = LangiumServices & AtlasAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AtlasModule: Module<AtlasServices, PartialLangiumServices & AtlasAddedServices> = {
    references: {
        NameProvider: () => new AtlasNameProvider()
    },
    validation: {
        AtlasValidator: () => new AtlasValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAtlasServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Atlas: AtlasServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        AtlasGeneratedSharedModule
    );
    const Atlas = inject(
        createDefaultModule({ shared }),
        AtlasGeneratedModule,
        AtlasModule
    );
    shared.ServiceRegistry.register(Atlas);
    registerValidationChecks(Atlas);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Atlas };
}
