/******************************************************************************
 * Adapted from processr-atlas (originally generated by langium-cli 4.2.0).
 ******************************************************************************/

import type { LangiumSharedCoreServices, LangiumCoreServices, LangiumGeneratedCoreServices, LangiumGeneratedSharedCoreServices, LanguageMetaData, Module } from 'langium';
import { AtlasAstReflection } from './ast.js';
import { AtlasGrammar } from './grammar.js';

export const AtlasLanguageMetaData = {
    languageId: 'atlas',
    fileExtensions: ['.prat'],
    caseInsensitive: false,
    mode: 'development'
} as const satisfies LanguageMetaData;

export const AtlasGeneratedSharedModule: Module<LangiumSharedCoreServices, LangiumGeneratedSharedCoreServices> = {
    AstReflection: () => new AtlasAstReflection()
};

export const AtlasGeneratedModule: Module<LangiumCoreServices, LangiumGeneratedCoreServices> = {
    Grammar: () => AtlasGrammar(),
    LanguageMetaData: () => AtlasLanguageMetaData,
    parser: {}
};
